### ISSUE TITLE
How to display diff image on reporter?

### ISSUE THREAD

**Issue by fedika** [wswebcreation/wdio-image-comparison-service#55] opened 2021-02-03 13:34 UTC
Hi,

Thank you for providing wdio-image-comparison-service.
We have implemented this module and it works, we can get the screenshot file in diff folder that shows us what is the difference between the actual and base image.
But we cannot find its diff screenshot in our Allure Reporter html, we realize it is because of the different stored location. Based on XML file, Allure reporter displays the screenshot from its location, allure-results folder, which different from diff folder.

Is there any example regarding display the diff screenshot file in reporter?

**Environment (please complete the following information):**
 - Node.js version: 12.19.0
 - NPM version: 6.14.8
 - Browser name and version: Chrome 88
 - Platform name and version: Linux Mint 20
 - WebdriverIO version: 6.12.1
 - wdio-image-comparison-service version: 2.0.0
 - Allure reporter: 6.11.0

**Comment by wswebcreation** [comment] 2021-02-05 09:00
Hi @fedika 

This all depends on how you want to implement this in Allure, this module will provide all the needed data (you can get back all folders and file names if you want). You just need to integrate it yourself with Allure.

Going to close this one because it's not related to this module

**Closed by wswebcreation** 2021-02-05 09:00 UTC

**Comment by lacell75** [comment] 2021-03-15 10:15
My code snippset :
const { addAttachment, addDescription } = require('@wdio/allure-reporter').default;`
// Added diff for visual regression in report

  if (scenario.result.message && scenario.result.message.toString().includes('The comparison has failed')) {
    const pathScreenshot = path.resolve(
      `.tmp/diff/desktop_${browserName.toLowerCase().replace('edge', 'microsoftedge')}`,
      `${browser.params.screenshotName.replace(/ /g, '_')}.png`
    );

    const imageTo64 = base64Img.base64Sync(pathScreenshot).replace('data:image/png;base64,', '');
    allureReport.addAttachment('Diff image', Buffer.from(imageTo64, 'base64'), 'image/png');
  }`

**Comment by hughleo** [comment] 2021-03-31 16:20
this is how we do it: https://hughmccamphill.com/blog/wdio-image-comparison/
