### ISSUE TITLE
V6 support

### ISSUE THREAD

**Issue by ryuran** [wswebcreation/wdio-image-comparison-service#33] opened 2020-04-10 16:13 UTC
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/wswebcreation/wdio-image-comparison-service) and submit a pull request

**Describe the improvement**

I'd like to report
- [ ] Unclear documentation
- [ ] A typo
- [x] Missing documentation
- [ ] Other

**Description of the improvement / report**
The current version seems not compatible with webdriverio v6.
It's not noticed in readme.

**Comment by anto-ac** [comment] 2020-04-10 16:23
It is compatible. I’m using it.

**Comment by wswebcreation** [comment] 2020-04-11 05:31
Yep, it is compatible with V6, closing it for now because there is also no logs or description what the problem is

**Closed by wswebcreation** 2020-04-11 05:31 UTC

**Comment by ryuran** [comment] 2020-04-11 14:50
Do we have an example? @anto-ac @wswebcreation
I have some issue to integrate it.

**Comment by anto-ac** [comment] 2020-04-11 15:37
What are the issues?
