### ISSUE TITLE
Screenshots taken at random lower screen size

### ISSUE THREAD

**Issue by llanni** [wswebcreation/wdio-image-comparison-service#80] opened 2022-01-24 18:25 UTC
**Environment (please complete the following information):**
 - Node.js version: 16.13.1
 - NPM version: 8.1.2
 - Browser name and version: Chrome 97
 - Platform name and version: macOS Monterey 12.1
 - WebdriverIO version: 7.16.13
 - wdio-image-comparison-service version: 7.2.6

**Config of WebdriverIO + wdio-image-comparison-service**
 ```js
   [
      'image-comparison',
      imageComparisonConfig({
        formatImageName: '{tag}-{width}x{height}',
        baselineFolder: BASE_LINE_DESKTOP_DIR,
        screenshotPath: SCREENSHOT_DESKTOP_DIR
      })
    ]
```

**Describe the bug**
When I run the visual comparison as part of bdd serenity-js, the screenshots taken by the wdio-image-comparison-service in desktop configuration are not 1920x1080 but they are 1920x<randomValue> where <randomValue> changes at each execution and it goes normally around 960, 970, 974, 978 etc.
Examples of different runs of the same visual comparison:
xxxx-1920x978.png
xxxx-1920x980.png
xxxx-1920x972.png

This makes the comparison vs the static baseline at 1920x1080 fail.
The issue only happens if I test in desktop mode, if I test on lower resolution (mobile/tablet or mobile/smartphone) the screenshots are always taken at the right resolutions (768x1024 and 375x812).

I run my bdd in normal mode (not headless) on a UHD screen (3180x2160) or MBP 2019 Retina Display (2880×1800).

**To Reproduce**
See the description of the bug.

**Expected behavior**
Take an actual screenshot at always the expected resolution 1920x1080 and not a lower resolution with a randomly changing y-value.

**Log**
N/A

**Additional context**
N/A

**Comment by wswebcreation** [comment] 2022-01-25 06:26
Hi @llanni 

Thanks for the issue, can you provide a reproducible example? I don't have this issues on my Mac

**Comment by llanni** [comment] 2022-01-28 11:39
@wswebcreation thanks a lot for your message, unfortunately I can reproduce the issue on a project that I cannot share (not my IP), I totally appreciate it is hard/impossible to debug something without a concrete example of the issue, so it is ok if you want to close it as not reproducible unless there is another way to show the issue?
Thanks for the support in any case

**Comment by wswebcreation** [comment] 2022-01-31 05:27
Hi @llanni 

I totally understand, but I'm not asking you to share your project code here, maybe yo have a sample project that behaves the same, if so then please provide it so I can see if I can find what's wrong

**Comment by llanni** [comment] 2022-01-31 06:19
Hi @wswebcreation,

I will try my best to isolate a sample project where it should be possible to reproduce the issue, I will link it here as soon as I can.
Thanks a lot for the help, much appreciated :)

**Comment by mhdSid** [comment] 2022-02-20 06:35
I'm having a similar issue. It doesn't happen regularly, but in our team, we run image comparison in docker environment under linux. There is a jenkins job that triggers wdio tests. I often encounter a failure in baeLine images because the actual ones are taken at a different screen resolution.

**Comment by wswebcreation** [comment] 2022-02-20 06:41
Hi @mhdSid 

It would be great to have a reproducible example so I can debug, without it I can't do anything about it. Thanks

**Comment by mhdSid** [comment] 2022-02-20 07:00
I'll share a example using code sandbox. I'll try to share it between today and tomorrow!

**Comment by mhdSid** [comment] 2022-02-21 08:17
@wswebcreation Please check this code sandbox which contains similar configuration  to the one we are using in production.
Kindly note, that this is ran in Jenkins with docker configured in addition to ubunutu OS.
https://codesandbox.io/s/inspiring-browser-jv7y5x?file=/package.json

**Comment by mhdSid** [comment] 2022-02-21 08:21
Docker is configured with node v12.13.0 and npm v6.12.0

**Comment by mhdSid** [comment] 2022-02-21 08:26
The issue won't happen straight away, but it's existing!

**Comment by mhdSid** [comment] 2022-02-21 08:38
Please let me know if you want me to prepare a runnable Docker env

**Comment by mhdSid** [comment] 2022-02-24 09:54
@wswebcreation 

I think the issue lies in this method:
https://github.com/wswebcreation/webdriver-image-comparison/blob/8e80b9ce6fd5e5fe2ec0e3376ef3fa955d02ce40/lib/methods/screenshots.ts#L274

It checks and confirms that images height, but it doesn't reassure that the widths will be the same, therefore, a check that confirms images width match should be implemented.

**Comment by mhdSid** [comment] 2022-02-24 12:01
After debuging, I found that the cause of diffence in comparison is due to text rendering from our components. My side of the story can be resolved!

**Comment by wswebcreation** [comment] 2022-03-06 07:50
Thanks for the update, closing it for now

**Closed by wswebcreation** 2022-03-06 07:50 UTC
Labels: more info needed
